blank_issues_enabled: true
contact_links:
  - name: 技術的な内容以外のご要望・ご提案
    url: https://tally.so/embed/3lB5gV?alignLeft=1&hideTitle=1&transparentBackground=1&dynamicHeight=1
    about: 技術的な内容以外のご要望等は、このリポジトリではなく、フォームにてご連絡ください。
